/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.tempomedic.vista;

import java.awt.CardLayout;

/**
 *
 * @author Santiago González
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName());

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpContenedorPrincipal = new javax.swing.JPanel();
        jpVistaHoy = new javax.swing.JPanel();
        jpVistaMedicamentos = new javax.swing.JPanel();
        jpVistaCitas = new javax.swing.JPanel();
        jpVistaAjustes = new javax.swing.JPanel();
        jpBarraInferior = new javax.swing.JPanel();
        btnHoy = new javax.swing.JButton();
        btnMedicamentos = new javax.swing.JButton();
        btnCitas = new javax.swing.JButton();
        btnAjustes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpContenedorPrincipal.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout jpVistaHoyLayout = new javax.swing.GroupLayout(jpVistaHoy);
        jpVistaHoy.setLayout(jpVistaHoyLayout);
        jpVistaHoyLayout.setHorizontalGroup(
            jpVistaHoyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
        );
        jpVistaHoyLayout.setVerticalGroup(
            jpVistaHoyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );

        jpContenedorPrincipal.add(jpVistaHoy, "hoy");

        javax.swing.GroupLayout jpVistaMedicamentosLayout = new javax.swing.GroupLayout(jpVistaMedicamentos);
        jpVistaMedicamentos.setLayout(jpVistaMedicamentosLayout);
        jpVistaMedicamentosLayout.setHorizontalGroup(
            jpVistaMedicamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
        );
        jpVistaMedicamentosLayout.setVerticalGroup(
            jpVistaMedicamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );

        jpContenedorPrincipal.add(jpVistaMedicamentos, "medicamentos");

        javax.swing.GroupLayout jpVistaCitasLayout = new javax.swing.GroupLayout(jpVistaCitas);
        jpVistaCitas.setLayout(jpVistaCitasLayout);
        jpVistaCitasLayout.setHorizontalGroup(
            jpVistaCitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
        );
        jpVistaCitasLayout.setVerticalGroup(
            jpVistaCitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );

        jpContenedorPrincipal.add(jpVistaCitas, "citas");

        javax.swing.GroupLayout jpVistaAjustesLayout = new javax.swing.GroupLayout(jpVistaAjustes);
        jpVistaAjustes.setLayout(jpVistaAjustesLayout);
        jpVistaAjustesLayout.setHorizontalGroup(
            jpVistaAjustesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
        );
        jpVistaAjustesLayout.setVerticalGroup(
            jpVistaAjustesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );

        jpContenedorPrincipal.add(jpVistaAjustes, "ajustes");

        getContentPane().add(jpContenedorPrincipal, java.awt.BorderLayout.CENTER);

        jpBarraInferior.setBackground(new java.awt.Color(59, 106, 118));
        jpBarraInferior.setMaximumSize(new java.awt.Dimension(360, 32767));
        jpBarraInferior.setMinimumSize(new java.awt.Dimension(360, 23));
        jpBarraInferior.setPreferredSize(new java.awt.Dimension(360, 50));
        jpBarraInferior.setLayout(new java.awt.GridLayout(1, 4));

        btnHoy.setText("Hoy");
        btnHoy.addActionListener(this::btnHoyActionPerformed);
        jpBarraInferior.add(btnHoy);

        btnMedicamentos.setText("Medicamentos");
        btnMedicamentos.addActionListener(this::btnMedicamentosActionPerformed);
        jpBarraInferior.add(btnMedicamentos);

        btnCitas.setText("Citas");
        btnCitas.addActionListener(this::btnCitasActionPerformed);
        jpBarraInferior.add(btnCitas);

        btnAjustes.setText("Ajustes");
        btnAjustes.addActionListener(this::btnAjustesActionPerformed);
        jpBarraInferior.add(btnAjustes);

        getContentPane().add(jpBarraInferior, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAjustesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjustesActionPerformed
        ((java.awt.CardLayout) jpContenedorPrincipal.getLayout()).show(jpContenedorPrincipal, "ajustes");
    }//GEN-LAST:event_btnAjustesActionPerformed

    private void btnHoyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHoyActionPerformed
        ((java.awt.CardLayout) jpContenedorPrincipal.getLayout()).show(jpContenedorPrincipal, "hoy");
    }//GEN-LAST:event_btnHoyActionPerformed

    private void btnMedicamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMedicamentosActionPerformed
        ((java.awt.CardLayout) jpContenedorPrincipal.getLayout()).show(jpContenedorPrincipal, "medicamentos");
    }//GEN-LAST:event_btnMedicamentosActionPerformed

    private void btnCitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCitasActionPerformed
        ((java.awt.CardLayout) jpContenedorPrincipal.getLayout()).show(jpContenedorPrincipal, "citas");
    }//GEN-LAST:event_btnCitasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAjustes;
    private javax.swing.JButton btnCitas;
    private javax.swing.JButton btnHoy;
    private javax.swing.JButton btnMedicamentos;
    private javax.swing.JPanel jpBarraInferior;
    private javax.swing.JPanel jpContenedorPrincipal;
    private javax.swing.JPanel jpVistaAjustes;
    private javax.swing.JPanel jpVistaCitas;
    private javax.swing.JPanel jpVistaHoy;
    private javax.swing.JPanel jpVistaMedicamentos;
    // End of variables declaration//GEN-END:variables
}
