/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.tempomedic.vista;

import java.awt.CardLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;

/**
 *
 * @author Santiago González
 */
public class VentanaLogin extends javax.swing.JFrame {
    
    private CardLayout navegadorTarjetas;

    /**
     * Creates new form VentanaLogin
     */
    public VentanaLogin() {
        initComponents();
        navegadorTarjetas = (CardLayout) jpContenedorLogin.getLayout();
        configurarEventosNavegacion();
    }
    
    private void configurarEventosNavegacion() {
        btnIrARegistro.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                navegadorTarjetas.show(jpContenedorLogin, "jpTarjetaRegistro");
            }
        });
        
        btnVolverLogin.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                navegadorTarjetas.show(jpContenedorLogin, "jpTarjetaLogin");
            }
        });
        
        btnIngresar.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                procesarInicioSesion();
            }
        });
        
        btnGuardarRegistro.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                procesarRegistroNuevoUsuario();
            }
        });
    }
    
    private void procesarInicioSesion() {
        String correo = txtCorreo.getText().trim();
        String contrasena = new String(txtContrasena.getPassword()); 

        if (correo.isEmpty() || contrasena.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, completa todos los campos.", "Campos vacíos", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (correo.equals("admin@admin.com") && contrasena.equals("1234")) {
            VentanaPrincipal principal = new VentanaPrincipal();
            principal.setLocationRelativeTo(null);
            principal.setVisible(true);
            
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Correo o contraseña incorrectos.", "Error de acceso", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void procesarRegistroNuevoUsuario() {
        String correo = txtRegCorreo.getText().trim();
        String nuevaContrasena = new String(txtRegContrasena.getPassword());
        String contrasenaRep = new String(txtRegContrasenaRep.getPassword());

        if (correo.isEmpty() || nuevaContrasena.isEmpty() || contrasenaRep.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Todos los campos de registro son obligatorios.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (!nuevaContrasena.equals(contrasenaRep)) {
            JOptionPane.showMessageDialog(this, "Las contraseñas no coinciden. Por favor, verifícalas.", "Error de validación", JOptionPane.ERROR_MESSAGE);
            return;
        }

        JOptionPane.showMessageDialog(this, "¡Usuario " + correo + " registrado con éxito!");

        txtRegCorreo.setText("");
        txtRegContrasena.setText("");
        txtRegContrasenaRep.setText("");

        navegadorTarjetas.show(jpContenedorLogin, "jpTarjetaLogin");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpContenedorLogin = new javax.swing.JPanel();
        jpTarjetaLogin = new javax.swing.JPanel();
        lblCorreo = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        lblContrasena = new javax.swing.JLabel();
        txtContrasena = new javax.swing.JPasswordField();
        btnIngresar = new javax.swing.JButton();
        btnIrARegistro = new javax.swing.JButton();
        jpTarjetaRegistro = new javax.swing.JPanel();
        lblRegCorreo = new javax.swing.JLabel();
        txtRegCorreo = new javax.swing.JTextField();
        lblRegContrasena = new javax.swing.JLabel();
        txtRegContrasena = new javax.swing.JPasswordField();
        lblRegContrasenaRep = new javax.swing.JLabel();
        txtRegContrasenaRep = new javax.swing.JPasswordField();
        btnGuardarRegistro = new javax.swing.JButton();
        btnVolverLogin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(360, 640));

        jpContenedorLogin.setMinimumSize(new java.awt.Dimension(360, 640));
        jpContenedorLogin.setLayout(new java.awt.CardLayout());

        jpTarjetaLogin.setMinimumSize(new java.awt.Dimension(360, 640));
        jpTarjetaLogin.setName("tarjetaLogin"); // NOI18N
        jpTarjetaLogin.setPreferredSize(new java.awt.Dimension(360, 640));

        lblCorreo.setText("Correo:");

        txtCorreo.addActionListener(this::txtCorreoActionPerformed);

        lblContrasena.setText("Contraseña:");

        txtContrasena.addActionListener(this::txtContrasenaActionPerformed);

        btnIngresar.setText("Iniciar Sesión");

        btnIrARegistro.setLabel("Crear cuenta");
        btnIrARegistro.addActionListener(this::btnIrARegistroActionPerformed);

        javax.swing.GroupLayout jpTarjetaLoginLayout = new javax.swing.GroupLayout(jpTarjetaLogin);
        jpTarjetaLogin.setLayout(jpTarjetaLoginLayout);
        jpTarjetaLoginLayout.setHorizontalGroup(
            jpTarjetaLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTarjetaLoginLayout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addGroup(jpTarjetaLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpTarjetaLoginLayout.createSequentialGroup()
                        .addComponent(lblContrasena)
                        .addGap(18, 18, 18)
                        .addComponent(txtContrasena, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpTarjetaLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jpTarjetaLoginLayout.createSequentialGroup()
                            .addComponent(lblCorreo)
                            .addGap(18, 18, 18)
                            .addComponent(txtCorreo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jpTarjetaLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnIrARegistro)
                            .addComponent(btnIngresar))))
                .addContainerGap(113, Short.MAX_VALUE))
        );
        jpTarjetaLoginLayout.setVerticalGroup(
            jpTarjetaLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTarjetaLoginLayout.createSequentialGroup()
                .addGap(279, 279, 279)
                .addGroup(jpTarjetaLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCorreo)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpTarjetaLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblContrasena)
                    .addComponent(txtContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(btnIngresar)
                .addGap(47, 47, 47)
                .addComponent(btnIrARegistro)
                .addContainerGap(193, Short.MAX_VALUE))
        );

        jpContenedorLogin.add(jpTarjetaLogin, "jpTarjetaLogin");

        jpTarjetaRegistro.setMinimumSize(new java.awt.Dimension(360, 640));
        jpTarjetaRegistro.setName("tarjetaRegistro"); // NOI18N
        jpTarjetaRegistro.setPreferredSize(new java.awt.Dimension(360, 640));

        lblRegCorreo.setText("Correo:");

        txtRegCorreo.addActionListener(this::txtRegCorreoActionPerformed);

        lblRegContrasena.setText("Contraseña:");

        txtRegContrasena.addActionListener(this::txtRegContrasenaActionPerformed);

        lblRegContrasenaRep.setText("Repetir contraseña:");

        txtRegContrasenaRep.addActionListener(this::txtRegContrasenaRepActionPerformed);

        btnGuardarRegistro.setLabel("Crear cuenta");

        btnVolverLogin.setText("¿Ya tienes cuenta? Inicia sesión");
        btnVolverLogin.addActionListener(this::btnVolverLoginActionPerformed);

        javax.swing.GroupLayout jpTarjetaRegistroLayout = new javax.swing.GroupLayout(jpTarjetaRegistro);
        jpTarjetaRegistro.setLayout(jpTarjetaRegistroLayout);
        jpTarjetaRegistroLayout.setHorizontalGroup(
            jpTarjetaRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTarjetaRegistroLayout.createSequentialGroup()
                .addGroup(jpTarjetaRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpTarjetaRegistroLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jpTarjetaRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jpTarjetaRegistroLayout.createSequentialGroup()
                                .addComponent(lblRegContrasenaRep)
                                .addGap(18, 18, 18)
                                .addComponent(txtRegContrasenaRep, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnGuardarRegistro)
                            .addGroup(jpTarjetaRegistroLayout.createSequentialGroup()
                                .addGroup(jpTarjetaRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblRegCorreo)
                                    .addComponent(lblRegContrasena))
                                .addGap(18, 18, 18)
                                .addGroup(jpTarjetaRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtRegCorreo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtRegContrasena, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jpTarjetaRegistroLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(btnVolverLogin)))
                .addGap(0, 92, Short.MAX_VALUE))
        );
        jpTarjetaRegistroLayout.setVerticalGroup(
            jpTarjetaRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTarjetaRegistroLayout.createSequentialGroup()
                .addGap(248, 248, 248)
                .addGroup(jpTarjetaRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRegCorreo)
                    .addComponent(txtRegCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jpTarjetaRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRegContrasena)
                    .addComponent(txtRegContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpTarjetaRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRegContrasenaRep)
                    .addComponent(txtRegContrasenaRep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(btnGuardarRegistro)
                .addGap(42, 42, 42)
                .addComponent(btnVolverLogin)
                .addContainerGap(162, Short.MAX_VALUE))
        );

        jpContenedorLogin.add(jpTarjetaRegistro, "jpTarjetaRegistro");

        getContentPane().add(jpContenedorLogin, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtContrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContrasenaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContrasenaActionPerformed

    private void btnIrARegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIrARegistroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIrARegistroActionPerformed

    private void txtRegContrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRegContrasenaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRegContrasenaActionPerformed

    private void btnVolverLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVolverLoginActionPerformed

    private void txtRegCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRegCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRegCorreoActionPerformed

    private void txtCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoActionPerformed

    private void txtRegContrasenaRepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRegContrasenaRepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRegContrasenaRepActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaLogin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardarRegistro;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JButton btnIrARegistro;
    private javax.swing.JButton btnVolverLogin;
    private javax.swing.JPanel jpContenedorLogin;
    private javax.swing.JPanel jpTarjetaLogin;
    private javax.swing.JPanel jpTarjetaRegistro;
    private javax.swing.JLabel lblContrasena;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblRegContrasena;
    private javax.swing.JLabel lblRegContrasenaRep;
    private javax.swing.JLabel lblRegCorreo;
    private javax.swing.JPasswordField txtContrasena;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JPasswordField txtRegContrasena;
    private javax.swing.JPasswordField txtRegContrasenaRep;
    private javax.swing.JTextField txtRegCorreo;
    // End of variables declaration//GEN-END:variables
}
